import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/page";
import Footer from "@/components/footer/page";

import { DM_Sans } from "next/font/google";

const dmsans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dmsans",
});

const clashDisplay = localFont({
  src: "./fonts/ClashDisplayBold.woff",
  variable: "--font-ClashDisplay",
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${dmsans.variable} ${clashDisplay.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
